mysite/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
    url(r'^todo/', include('todolist.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

polls/urls.py
from django.conf.urls import url
from . import views
app_name = 'polls'
urlpatterns = [

    # Index Url
    url(r'^$', views.index, name='index'),

    # Details of question
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),

    # results of question
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),

    # vote for question
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),

    #testUrl
    url(r'^test/(?P<testId>[0-9]+)/$', views.testView, name='test'),
]

todolist/urls.py
from django.conf.urls import url
from . import views
app_name = 'todolist'
urlpatterns = [

    # Index Url
    url(r'^$', views.index, name='index'),

]

polls/models.py
from __future__ import unicode_literals

import datetime
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone
# Create your models here.

@python_2_unicode_compatible
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


@python_2_unicode_compatible
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

todolist/models.py
from __future__ import unicode_literals

import datetime
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone
# Create your models here.


@python_2_unicode_compatible
class Task(models.Model):
    taskText = models.CharField(max_length=300)
    startDate = models.DateTimeField()
    deadLineDate = models.DateTimeField()
    isDone = models.BooleanField(default=False)


    def __str__(self):
        return self.taskText

    def isOverdue(self):
        return self.deadLineDate < datetime.datetime.now()

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from .models import Question
from django.core.handlers.wsgi import WSGIRequest
# Create your views here.

def index(request):
    print 'Were here'
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {
        'latest_question_list':latest_question_list,
    }
    return render(request,'polls/index.html', context )#HttpResponse(template.render(context, request))

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question':question}
    return  render(request, 'polls/detail.html', context)

def results(request, question_id):
    response = "You're looking at the results of question %s"
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s" % question_id)

def testView(request, testId):
    context = {'testId':testId, 'lst':[1,2,3,4,5]}
    return render(request, 'polls/test.html', context)

todolist/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import Task
# Create your views here.

def index(request):
    taskList = Task.objects.all().order_by("deadLineDate")
    context = {
        "taskList" : taskList
    }
    return render(request, 'todolist/index.html',context)

polls/templates/polls/detail.html
<!--
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>
-->
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/test.html
<!DOCTYPE html>
{% load static %}
<html>
   <link>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

       <!-- <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
       <script type="text/javascript" src="{% static "polls/tmpScript.js" %}" ></script>
       <link href="{% static "bootstrap/css/bootstrap.css"%}" rel="stylesheet">
      <title>HTML Document</title> -->
   </head>
   <body>
   <header onkeyup="true">
   </header>
    <div draggable="false">
       <table border="1" width="100%">
 <thead>
 	<tr><td>...header information...</td></tr>
 </thead>
 <tfoot>
 	<tr><td>...footer information...</td></tr>
 </tfoot>
 <tbody>
 	<tr><td>...first row of block one data...</td></tr>
 </tbody>
 <tbody>
 	<tr><td>...first row of block two data...</td></tr>
 </tbody>
 </table>
    </div>
   </body>
</html>

todolist/templates/todolist/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ToDoList</title>
    <link rel="stylesheet" type="text/css" href="{% static 'todolist/styles/index.css' %}" />
</head>

<nav>

</nav>

<body>
    <div id = 'main'>
        <p id="greeting">
            Hello!
        </p>
        <p id="smth">
            Second Line
        </p>
        {% for item in taskList %}
            <div class="taskContainer">
                <div class="taskText">
                    <p class="task">
                        {{ item.taskText }}
                    </p>
                </div>
                <div class = "taskDeadLineDate">
                    <p class="task">
                        {{ item.deadLineDate }}
                    </p>
                </div>
            </div>

        {% endfor %}

    </div>
</body>
</html>